-- MySQL Script generated by MySQL Workbench
-- Wed 28 Aug 2019 15:15:36 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Sex` ENUM("M", "F", "T") NULL,
  `age_diagnosis` DATE NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mutation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mutation` (
  `idMut` INT NOT NULL AUTO_INCREMENT,
  `chromosome` VARCHAR(2) NULL,
  `chromosome_location` VARCHAR(45) NULL,
  PRIMARY KEY (`idMut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gene` (
  `idGene` INT NOT NULL AUTO_INCREMENT,
  `gene_name` VARCHAR(50) NULL,
  `chromosomal_location` VARCHAR(45) NULL,
  `description` TEXT(255) NULL,
  PRIMARY KEY (`idGene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`XREF - gene/mutation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`XREF - gene/mutation` (
  `idCROSS REF` INT NOT NULL AUTO_INCREMENT,
  `gene_identifier` INT NULL,
  `mutation_identifier` INT NULL,
  PRIMARY KEY (`idCROSS REF`),
  INDEX `fk_XREF - gene/mutation_1_idx` (`gene_identifier` ASC) VISIBLE,
  INDEX `fk_XREF - gene/mutation_2_idx` (`mutation_identifier` ASC) VISIBLE,
  CONSTRAINT `fk_XREF - gene/mutation_1`
    FOREIGN KEY (`gene_identifier`)
    REFERENCES `mydb`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_XREF - gene/mutation_2`
    FOREIGN KEY (`mutation_identifier`)
    REFERENCES `mydb`.`Mutation` (`idMut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnosis` (
  `idDiagnosis` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `affected_gene_id` INT NULL,
  `mutation` INT NULL,
  PRIMARY KEY (`idDiagnosis`),
  INDEX `fk_Diagnosis_1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_Diagnosis_2_idx` (`affected_gene_id` ASC) VISIBLE,
  INDEX `fk_Diagnosis_3_idx` (`mutation` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnosis_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnosis_2`
    FOREIGN KEY (`affected_gene_id`)
    REFERENCES `mydb`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnosis_3`
    FOREIGN KEY (`mutation`)
    REFERENCES `mydb`.`Mutation` (`idMut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
